import React from 'react';

import type { Metadata } from 'next';

import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';

import { StyledRoot } from '@/StyledRoot';
import Navbar from '@/app/components/Navbar/Navbar';
import AuthProvider from '@/app/providers/authProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <AuthProvider>
            <Navbar />
            <StyledRoot>{children}</StyledRoot>
          </AuthProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
